api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_details'),
    url(r'^wallets/$', views.WalletListView.as_view(), name='wallet_list'),
    url(r'^wallets/(?P<pk>\d+)/$', views.WalletDetailView.as_view(), name='wallet_details'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category_details'),
    url(r'^transactions/$', views.TransactionListView.as_view(), name='transaction_list'),
    url(r'^transactions/(?P<pk>\d+)/$', views.TransactionDetailView.as_view(), name='transaction_details'),
    url(r'^budgets/$', views.BudgetListView.as_view(), name='budget_list'),
    url(r'^budgets/(?P<pk>\d+)/$', views.BudgetDetailView.as_view(), name='budget_details'),
    url(r'^savings/$', views.SavingListView.as_view(), name='saving_list'),
    url(r'^savings/(?P<pk>\d+)/$', views.SavingDetailView.as_view(), name='saving_details'),
    url(r'^$', views.api_root, name='api_root'),
]

transactions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^wallet/list/$', views.wallet_list, name='wallet_list'),
    url(r'^wallet/detail/(?P<id>\d+)/$', views.wallet_details, name='wallet_details'),
    url(r'^wallet/create/$', views.wallet_create, name='wallet_create'),
    url(r'^wallet/delete/(?P<pk>\d+)/$', views.WalletDelete.as_view(), name='wallet_delete'),
    url(r'^wallet/update/(?P<pk>\d+)/$', views.WalletUpdate.as_view(), name='wallet_update'),
    url(r'^category/list/$', views.category_list, name='category_list'),
    url(r'^category/detail/(?P<id>\d+)/$', views.category_details, name='category_details'),
    url(r'^category/create/$', views.category_create, name='category_create'),
    url(r'^category/delete/(?P<pk>\d+)/$', views.CategoryDelete.as_view(), name='category_delete'),
    url(r'^category/update/(?P<pk>\d+)/$', views.CategoryUpdate.as_view(), name='category_update'),
    url(r'^transaction/list/$', views.transaction_list, name='transactions_list'),
    url(r'^transaction/detail/(?P<id>\d+)/$', views.transaction_detail, name='transaction_details'),
    url(r'^transaction/create/$', views.transaction_create, name='transaction_create'),
    url(r'^transaction/delete/(?P<pk>\d+)/$', views.TransactionDelete.as_view(), name='transaction_delete'),
    url(r'^transaction/update/(?P<pk>\d+)/$', views.TransactionUpdate.as_view(), name='transaction_update'),
    url(r'^transaction/filter/$', views.transaction_filter, name='transaction_filter'),
    url(r'^transaction/create_recurring/$', views.recurring_transaction_create, name='recurring_create'),
    url(r'^export/csv/$', views.export_transactions_csv, name='export_transactions_csv'),
    url(r'^export/xls/$', views.export_transactions_xls, name='export_transactions_xls'),

]

wallet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^transactions/', include('transactions.urls', namespace='wallet')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets')),
    url(r'^users/', include('users.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$', TemplateView.as_view(template_name='users/index.html')),
]

transactions/models.py
import django.utils.timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator
from django.db import models

from budgets.models import Budget, Saving

TRANSACTION_CHOICES = (
    ('income', 'Income'),
    ('expense', 'Expense'),
)


class Wallet(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    balance = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, related_name='wallets')
    description = models.TextField(blank=True, null=True, max_length=500)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wallet:wallet_details', args=[self.id])


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    user = models.ForeignKey(User, related_name='categories')

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wallet:category_details', args=[self.id])


class Transaction(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    type = models.CharField(choices=TRANSACTION_CHOICES, max_length=10)
    user = models.ForeignKey(User, related_name='transactions')
    wallet = models.ForeignKey(Wallet,
                               null=True,
                               blank=True,
                               related_name='transactions',
                               on_delete=models.DO_NOTHING)
    category = models.ForeignKey(Category,
                                 related_name='transactions',
                                 null=True,
                                 blank=True,
                                 on_delete=models.DO_NOTHING)
    budget = models.ForeignKey(Budget,
                               blank=True,
                               null=True,
                               default=None,
                               on_delete=models.DO_NOTHING)
    saving = models.ForeignKey(Saving,
                               blank=True,
                               null=True,
                               default=None,
                               on_delete=models.DO_NOTHING)
    date = models.DateField(verbose_name='Date of transaction',
                            default=django.utils.timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    notes = models.TextField(max_length=250, blank=True, null=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wallet:transaction_details', args=[self.id])

    def wallet_balance_adjust(self, wallet, transaction):
        if transaction.type == 'expense':
            wallet.balance -= transaction.amount
            return wallet.save()
        else:
            wallet.balance += transaction.amount
            return wallet.save()

transactions/views.py
import csv
import datetime

import xlwt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, UpdateView
from pure_pagination import PageNotAnInteger, Paginator

from budgets.models import Budget
from transactions.filters import TransactionFilter

from .forms import (CategoryCreateForm, TransactionCreateForm,
                    TransactionNextMonth, TransactionPrevMonth,
                    WalletCreateForm)
from .models import Category, Transaction, Wallet


@login_required
def wallet_list(request):
    current_user = request.user
    wallets = Wallet.objects.filter(user=current_user)
    return render(request, 'wallet/list.html', {'wallets': wallets})


@login_required
def wallet_details(request, id):
    wallet = get_object_or_404(Wallet, id=id)
    transactions = Transaction.objects.filter(wallet=wallet)
    return render(request, 'wallet/detail.html', {'wallet': wallet,
                                                  'transactions': transactions})


@login_required
def wallet_create(request):
    if request.method == 'POST':
        wallet_create_form = WalletCreateForm(request.POST)
        if wallet_create_form.is_valid():
            new_wallet = wallet_create_form.save(commit=False)
            new_wallet.user = request.user
            new_wallet.save()
            messages.success(request, 'Wallet created')
            return render(request, 'wallet/done.html')
    else:
        wallet_create_form = WalletCreateForm()
    return render(request, 'wallet/create.html', {'wallet_form': wallet_create_form})


class WalletDelete(DeleteView):
    model = Wallet
    template_name = 'wallet/wallet_confirm_delete.html'
    success_url = reverse_lazy('wallet:wallet_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(WalletDelete, self).dispatch(*args, **kwargs)


class WalletUpdate(UpdateView):
    model = Wallet
    fields = ['name', 'balance', 'description']
    template_name = 'wallet/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(WalletUpdate, self).dispatch(*args, **kwargs)


@login_required
def category_list(request):
    current_user = request.user
    categories = Category.objects.filter(user=current_user)
    return render(request, 'category/list.html', {'categories': categories})


@login_required
def category_details(request, id):
    category = get_object_or_404(Category, id=id)
    transactions = Transaction.objects.filter(category=category)
    return render(request, 'category/detail.html', {'category': category,
                                                    'transactions': transactions})


@login_required
def category_create(request):
    if request.method == 'POST':
        category_create_form = CategoryCreateForm(request.POST)
        if category_create_form.is_valid():
            new_category = category_create_form.save(commit=False)
            new_category.user = request.user
            new_category.save()
            messages.success(request, 'Category created')
            return render(request, 'category/done.html')
    else:
        category_create_form = CategoryCreateForm()
    return render(request, 'category/create.html', {'category_form': category_create_form})


class CategoryDelete(DeleteView):
    model = Category
    template_name = 'category/category_confirm_delete.html'
    success_url = reverse_lazy('wallet:category_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoryDelete, self).dispatch(*args, **kwargs)


class CategoryUpdate(UpdateView):
    model = Category
    template_name = 'category/update.html'
    form_class = CategoryCreateForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoryUpdate, self).dispatch(*args, **kwargs)


@login_required
def transaction_list(request, **kwargs):
    current_user = request.user

    if request.method == 'POST':
        next_month_form = TransactionNextMonth(request.POST)
        previous_month_form = TransactionPrevMonth(request.POST)

        if next_month_form.is_valid() and previous_month_form.is_valid():
            cd_next = next_month_form.cleaned_data
            cd_prev = previous_month_form.cleaned_data
            request.session['next_month'] = cd_next['month']
            request.session['prev_month'] = cd_prev['month']

            return HttpResponseRedirect('/transactions/transaction/list/')

    else:
        if request.session.get('next_month') is not None:
            next_month_form = TransactionNextMonth(
                initial={'month': request.session.get('next_month')+1})
            previous_month_form = TransactionPrevMonth(
                initial={'month': request.session.get('prev_month') - 1})
            objects = Transaction.objects.filter(user=current_user,
                                                 date__month=request.session.get('next_month'))
        else:
            next_month_form = TransactionNextMonth(
                initial={'month': datetime.date.today().month+1})
            previous_month_form = TransactionPrevMonth(
                initial={'month': datetime.date.today().month - 1})
            objects = Transaction.objects.filter(user=current_user,
                                                 date__month=datetime.date.today().month)

        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(objects, 10, request=request)
        transactions = p.page(page)
        return render(request, 'transaction/list.html',
                      {'transactions': transactions,
                       'next_month_form': next_month_form,
                       'prev_month_form': previous_month_form})


@login_required
def transaction_detail(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    return render(request, 'transaction/detail.html', {'transaction': transaction})


@login_required
def transaction_create(request):
    current_user = request.user
    if request.method == 'POST':
        transaction_create_form = TransactionCreateForm(current_user, request.POST)
        if transaction_create_form.is_valid():
            new_transaction = transaction_create_form.save(commit=False)
            new_transaction.user = current_user
            wallet = get_object_or_404(Wallet, name=new_transaction.wallet)
            new_transaction.wallet_balance_adjust(wallet, new_transaction)  # Adjust chosen wallet balance
            new_transaction.save()

            # assign budget if applicable:
            budgets = Budget.objects.filter(user=current_user)
            for budget in budgets:
                transactions = Transaction.objects.filter(
                    Q(date__gte=budget.date_from)
                    & Q(date__lte=budget.date_to)
                    & Q(category=budget.category))
                if budget.category == new_transaction.category and budget.active is True:
                    new_transaction.budget = budget
                    new_transaction.save()

                    # check if the budget has reached limit:
                    completion = budget.budget_completion(transactions)
                    if completion >= 100:
                        budget.finished, budget.finishing = True, False
                        messages.info(request,
                                      'You have reached the limit of your budget {}'
                                      .format(budget.name))
                    elif completion >= 80:
                        budget.finishing = True
                        messages.info(request,
                                      'You are almost at the limit of your budget {}'
                                      .format(budget.name))
                    budget.completion = completion
                    budget.save()
            messages.success(request, 'Transaction created')
            return render(request, 'transaction/done.html')
    else:

        transaction_create_form = TransactionCreateForm(current_user)
    return render(request, 'transaction/create.html',
                  {'transaction_form': transaction_create_form})


class TransactionDelete(DeleteView):
    model = Transaction
    template_name = 'transaction/transaction_confirm_delete.html'
    success_url = reverse_lazy('wallet:transactions_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TransactionDelete, self).dispatch(*args, **kwargs)


class TransactionUpdate(UpdateView):
    model = Transaction
    fields = ['name', 'type', 'wallet', 'category', 'date', 'amount', 'notes']
    template_name = 'transaction/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TransactionUpdate, self).dispatch(*args, **kwargs)


@login_required
def export_transactions_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="transactions.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', 'Type', 'Date', 'Wallet', 'Category', 'Amount', 'Notes'])

    transactions = Transaction.objects.filter(user=request.user).values_list(
        'name', 'type', 'date', 'wallet', 'category', 'amount', 'notes')
    for transaction in transactions:
        writer.writerow(transaction)
    return response


@login_required
def export_transactions_xls(request):
    response = HttpResponse(content_type='application/ms-excel')

transactions/templates/transaction/create.html
{% extends 'base.html' %}

{% block title %}Create new transaction{% endblock %}

{% block content %}
    <h1>Create new transaction</h1>
    <p>Fill in the details:</p>
    <form action="." method="post">
        {{ transaction_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create a transaction"></p>
    </form>

<script type="text/javascript">
  $(function(){
    $("#id_date").datepicker();
  });
</script>
{% endblock %}

transactions/templates/transaction/delete_done.html
{% extends 'base.html' %}

{% block title %}Transaction deleted{% endblock %}

{% block content %}
    <h1>Transaction deleted!</h1>
    <p>Transaction has been deleted.</p>
{% endblock %}

transactions/templates/transaction/detail.html
{% extends 'base.html' %}

{% block title %}Transaction: {{ transaction.name }}{% endblock %}

{% block content %}
    <div class="transaction-detail">
        <p>
            <h1><strong>{{ transaction.name }}</strong></h1>
            <strong>Wallet:</strong> {{ transaction.wallet }}<br>
            <strong>Type:</strong> {{ transaction.type }}<br>
            <strong>Category:</strong> {{ transaction.category }}<br>
            <strong>Description:</strong> {{ transaction.description }}<br>
            <strong>Date:</strong> {{ transaction.date }}<br>
            <strong>Amount:</strong> {{ transaction.amount }}<br>
            <strong>Notes:</strong> {{ transaction.notes }}<br>
        </p>
        <p><a href="{% url 'wallet:transaction_update' pk=transaction.id %}">Edit this transaction</a></p>
        <p><a href="{% url 'wallet:transaction_delete' pk=transaction.id %}">Delete this transaction</a></p>
    </div>
{% endblock %}

transactions/templates/transaction/done.html
{% extends 'base.html' %}

{% block title %}Transaction created{% endblock %}

{% block content %}
    <h1>Transaction created!</h1>
    <p>New transaction has been created.
        <p><a href="{% url 'wallet:transaction_create' %}">Add another transaction</a></p><br>
        <p><a href="{% url 'wallet:transactions_list' %}">Go back to transaction list</a></p>
    </p>
{% endblock %}

transactions/templates/transaction/filter.html
{% extends "base.html" %}

{% block title %}Filter transactions{% endblock %}

{% block content %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    <p>
        {% for obj in filter.qs %}
            <div class="transaction">
                <strong><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a></strong><br>
                Wallet: {{ obj.wallet }}<br>
                Amount: ${{ obj.amount }}
            </div><br>
        {% endfor %}
        <a href="{% url 'wallet:export_transactions_csv' %}">Export all transactions as CSV</a><br>
    </p>

<script type="text/javascript">
  $(function(){
    $("#id_date__gte").datepicker();
    $("#id_date__lte").datepicker();
  });
</script>
{% endblock %}

transactions/templates/transaction/list.html
{% extends 'base.html' %}

{% block title %}Your transactions{% endblock %}

{% block intro %}<h2>Your Transactions</h2>{% endblock %}

{% block content %}
    <h1>Your Transactions</h1>
    <p><a href="{% url 'wallet:transaction_filter' %}">Filter</a></p>
    <form action="." method="post">
        {{ prev_month_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Previous month"></p>
    </form>
    <form action="." method="post">
        {{ next_month_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Next month"></p>
    </form>
    <div class="transaction-list">
        {% for transaction in transactions.object_list %}
            <div class="transaction">
                <strong><a href="{{ transaction.get_absolute_url }}">{{ transaction.name }}</a></strong><br>
                Wallet: {{ transaction.wallet }}<br>
                Date: {{ transaction.date }}<br>
                Amount: ${{ transaction.amount }}
            </div><br>
        {% endfor %}
    </div>
    <div id="pagination">
        {{ transactions.render }}
    </div>
{% endblock %}

{% block menu %}
    <div>
        <a href="{% url 'wallet:transaction_create' %}">Create new transaction</a><br>
        <a href="{% url 'wallet:recurring_create' %}">Create recurring transaction</a>
    </div><br>
    <div><a href="{% url 'wallet:transaction_filter' %}">Filter transactions</a></div><br>
    <div>
        <a href="{% url 'wallet:export_transactions_csv' %}">Export all transactions as CSV</a><br>
        <a href="{% url 'wallet:export_transactions_xls' %}">Export all transactions as XLS</a>
    </div>
{% endblock %}

transactions/templates/transaction/transaction_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm transaction delete{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

transactions/templates/transaction/update.html
{% extends 'base.html' %}

{% block title %}Edit your transaction {{ transaction.name }}{% endblock %}

{% block content %}
    <div>
        <p><h1>Edit your transaction: {{ transaction.name }}</h1></p>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
        </form>
    </div>

<script type="text/javascript">
  $(function(){
    $("#id_date").datepicker();
  });
</script>
{% endblock %}