api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_details'),
    url(r'^wallets/$', views.WalletListView.as_view(), name='wallet_list'),
    url(r'^wallets/(?P<pk>\d+)/$', views.WalletDetailView.as_view(), name='wallet_details'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category_details'),
    url(r'^transactions/$', views.TransactionListView.as_view(), name='transaction_list'),
    url(r'^transactions/(?P<pk>\d+)/$', views.TransactionDetailView.as_view(), name='transaction_details'),
    url(r'^budgets/$', views.BudgetListView.as_view(), name='budget_list'),
    url(r'^budgets/(?P<pk>\d+)/$', views.BudgetDetailView.as_view(), name='budget_details'),
    url(r'^savings/$', views.SavingListView.as_view(), name='saving_list'),
    url(r'^savings/(?P<pk>\d+)/$', views.SavingDetailView.as_view(), name='saving_details'),
    url(r'^$', views.api_root, name='api_root'),
]

budgets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^budget/list/$', views.budgets_list, name='budgets_list'),
    url(r'^budget/details/(?P<id>\d+)/$', views.budget_details, name='budget_details'),
    url(r'^budget/create/$', views.budget_create, name='budget_create'),
    url(r'^budget/delete/(?P<pk>\d+)/$', views.BudgetDelete.as_view(), name='budget_delete'),
    url(r'^budget/update/(?P<pk>\d+)/$', views.BudgetUpdate.as_view(), name='budget_update'),
    url(r'^savings/list/$', views.savings_list, name='savings_list'),
    url(r'^savings/details/(?P<id>\d+)/$', views.saving_details, name='saving_details'),
    url(r'^savings/create/$', views.saving_create, name='saving_create'),
    url(r'^savings/delete/(?P<pk>\d+)/$', views.SavingDelete.as_view(), name='saving_delete'),
    url(r'^savings/update/(?P<pk>\d+)/$', views.SavingUpdate.as_view(), name='saving_update'),
    url(r'^savings/deposit/(?P<pk>\d+)/$', views.saving_deposit, name='saving_deposit'),
    url(r'^savings/withdraw/(?P<pk>\d+)/$', views.saving_withdraw, name='saving_withdraw'),
]

wallet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^transactions/', include('transactions.urls', namespace='wallet')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets')),
    url(r'^users/', include('users.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$', TemplateView.as_view(template_name='users/index.html')),
]

budgets/models.py
import django.utils.timezone
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Budget(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)  # amount budget is set for
    user = models.ForeignKey(User, related_name='budgets')
    wallet = models.ForeignKey('transactions.Wallet', on_delete=models.DO_NOTHING)
    category = models.ForeignKey('transactions.Category', on_delete=models.DO_NOTHING)
    date_from = models.DateField(default=django.utils.timezone.now)
    date_to = models.DateField(default=django.utils.timezone.now)
    finishing = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    completion = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        ordering = ['date_from', 'date_to', ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('budgets:budget_details', args=[self.id])

    def budget_completion(self, queryset):
        amount_set = self.amount
        amount_used = 0
        for transaction in queryset:
            if transaction.type == 'expense':
                amount_used += transaction.amount
            else:
                amount_used -= transaction.amount
        budget_used = (amount_used / amount_set) * 100  # budget use in percent
        return budget_used


class Saving(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    goal = models.DecimalField(max_digits=10, decimal_places=2)  # saving amount
    current_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    user = models.ForeignKey(User, related_name='savings')
    date_from = models.DateField()
    finished = models.BooleanField(default=False)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('budgets:saving_details', args=[self.id])

    def saving_completion(self):
        completion = (self.current_amount / self.goal) * 100
        return completion

budgets/forms.py
from django import forms

from transactions.models import Category, Wallet

from .models import Budget, Saving


class BudgetCreateForm(forms.ModelForm):
    field_order = ['name', 'wallet', 'category', 'amount', 'date_from', 'date_to']

    class Meta:
        model = Budget
        fields = ['name', 'amount', 'wallet', 'category', 'date_from', 'date_to']

    def __init__(self, user, *args, **kwargs):
        super(BudgetCreateForm, self).__init__(*args, **kwargs)
        self.fields['wallet'] = forms.ModelChoiceField(queryset=Wallet.objects.filter(user=user))
        self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.filter(user=user))


class SavingCreateForm(forms.ModelForm):
    field_order = ['name', 'goal', 'current_amount', 'date_from']

    class Meta:
        model = Saving
        fields = ['name', 'goal', 'current_amount', 'date_from']


class SavingDepositForm(forms.Form):
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    wallet = forms.ModelChoiceField(Wallet)

    def __init__(self, user, *args, **kwargs):
        super(SavingDepositForm, self).__init__(*args, **kwargs)
        self.fields['wallet'] = forms.ModelChoiceField(queryset=Wallet.objects.filter(user=user))

budgets/views.py
import django.utils.timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, UpdateView

from transactions.models import Category, Transaction, Wallet

from .forms import BudgetCreateForm, SavingCreateForm, SavingDepositForm
from .models import Budget, Saving


@login_required
def budgets_list(request):
    current_user = request.user
    budgets = Budget.objects.filter(user=current_user)
    return render(request, 'budgets/list.html', {'budgets': budgets})


@login_required
def budget_details(request, id):
    budget = get_object_or_404(Budget, id=id)
    transactions = Transaction.objects.filter(
        Q(date__gte=budget.date_from) & Q(date__lte=budget.date_to) & Q(category=budget.category))
    budget_used = Budget.budget_completion(budget, transactions)
    return render(request, 'budgets/details.html', {'budget': budget,
                                                    'budget_used': budget_used,
                                                    'transactions': transactions})


@login_required
def budget_create(request):
    current_user = request.user
    if request.method == 'POST':
        budget_create_form = BudgetCreateForm(current_user, request.POST)
        if budget_create_form.is_valid():
            new_budget = budget_create_form.save(commit=False)
            new_budget.user = request.user
            new_budget.save()
            messages.success(request, 'Budget created')
            return render(request, 'budgets/done.html')
    else:

        budget_create_form = BudgetCreateForm(current_user)
    return render(request, 'budgets/create.html',
                  {'budget_form': budget_create_form})


class BudgetDelete(DeleteView):
    model = Budget
    template_name = 'budgets/budget_confirm_delete.html'
    success_url = reverse_lazy('budgets:budgets_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BudgetDelete, self).dispatch(*args, **kwargs)


class BudgetUpdate(UpdateView):
    model = Budget
    fields = ['name', 'amount', 'wallet', 'category', 'date_from', 'date_to']
    template_name = 'budgets/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BudgetUpdate, self).dispatch(*args, **kwargs)


@login_required
def savings_list(request):
    current_user = request.user
    savings = Saving.objects.filter(user=current_user)
    return render(request, 'savings/list.html', {'savings': savings})


@login_required
def saving_details(request, id):
    saving = get_object_or_404(Saving, id=id)
    transactions = Transaction.objects.filter(saving=saving)
    completion = saving.saving_completion()
    return render(request, 'savings/details.html', {'saving': saving,
                                                    'transactions': transactions,
                                                    'completion': completion})


@login_required
def saving_create(request):
    current_user = request.user
    if request.method == 'POST':
        saving_create_form = SavingCreateForm(request.POST)
        if saving_create_form.is_valid():
            try:
                categories = Category.objects.get(name='Savings', user=current_user.id)
            except ObjectDoesNotExist:
                saving_category = Category(name='Savings', user=current_user)
                saving_category.save()
            new_saving = saving_create_form.save(commit=False)
            new_saving.user = request.user
            new_saving.save()
            messages.success(request, 'Saving created')
            return render(request, 'savings/done.html')
    else:

        saving_create_form = SavingCreateForm()
    return render(request, 'savings/create.html',
                  {'saving_form': saving_create_form})


class SavingDelete(DeleteView):
    model = Saving
    template_name = 'savings/saving_confirm_delete.html'
    success_url = reverse_lazy('budgets:savings_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SavingDelete, self).dispatch(*args, **kwargs)


class SavingUpdate(UpdateView):
    model = Saving
    fields = ['name', 'goal', 'date_from']
    template_name = 'savings/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SavingUpdate, self).dispatch(*args, **kwargs)


@login_required
def saving_deposit(request, pk):
    current_user = request.user
    if request.method == 'POST':
        saving_deposit_form = SavingDepositForm(current_user, request.POST)
        if saving_deposit_form.is_valid():
            cd = saving_deposit_form.cleaned_data
            saving = get_object_or_404(Saving, id=pk)
            wallet = get_object_or_404(Wallet, name=cd['wallet'])
            category = get_object_or_404(Category, name='Savings')

            wallet.balance -= cd['amount']
            transaction = Transaction(name='Saving deposit to: {}'.format(saving),
                                      type='expense',
                                      user=current_user,
                                      wallet=wallet,
                                      category=category,
                                      budget=None,
                                      saving=saving,
                                      date=django.utils.timezone.now(),
                                      amount=cd['amount'])
            saving.current_amount += cd['amount']  # adjust saving amount
            saving.save(), wallet.save(), transaction.save()
            messages.success(request, 'Deposit done')
            return redirect(saving)
    else:
        saving_deposit_form = SavingDepositForm(current_user)
    return render(request, 'savings/deposit.html',
                  {'deposit_form': saving_deposit_form})


@login_required
def saving_withdraw(request, pk):
    current_user = request.user
    if request.method == 'POST':
        saving_withdraw_form = SavingDepositForm(current_user, request.POST)
        if saving_withdraw_form.is_valid():
            cd = saving_withdraw_form.cleaned_data
            saving = get_object_or_404(Saving, id=pk)
            wallet = get_object_or_404(Wallet, name=cd['wallet'])
            category = get_object_or_404(Category, name='Savings')

            wallet.balance += cd['amount']
            transaction = Transaction(name='Saving withdraw from: {}'.format(saving),
                                      type='income',
                                      user=current_user,
                                      wallet=wallet,
                                      category=category,
                                      budget=None,
                                      saving=saving,
                                      date=django.utils.timezone.now(),
                                      amount=cd['amount'])
            saving.current_amount -= cd['amount']  # adjust saving amount
            saving.save(), wallet.save(), transaction.save()
            messages.success(request, 'Withdraw done')
            return redirect(saving)
    else:
        saving_deposit_form = SavingDepositForm(current_user)
    return render(request, 'savings/withdraw.html',
                  {'withdraw_form': saving_deposit_form})

budgets/templates/savings/create.html
{% extends 'base.html' %}

{% block title %}Create new saving{% endblock %}

{% block content %}
    <h1>Create new saving</h1>
    <p>Fill in the details:</p>
    <form action="." method="post">
        {{ saving_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create a saving"></p>
    </form>

<script type="text/javascript">
  $(function(){
    $("#id_date_from").datepicker();
  });
</script>
{% endblock %}

budgets/templates/savings/deposit.html
{% extends 'base.html' %}

{% block title %}Deposit to saving: {{ saving.name }}{% endblock %}

{% block content %}
    <h1>Deposit to saving: {{ saving.name }}</h1>
    <p>How much would you like to deposit?</p>
    <form action="." method="post">
        {{ deposit_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Deposit"></p>
    </form>
{% endblock %}

budgets/templates/savings/details.html
{% extends 'base.html' %}

{% block title %}Saving: {{ saving.name }}{% endblock %}

{% block content %}
    <div class="saving-detail">
        <p>
            <h1><strong>{{ saving.name }}</strong></h1><br>
            <h3>Saving progress: {{ completion|floatformat:'2' }}%</h3>
            <p>Running from {{ saving.date_from }}</p><br>
            <strong>Goal:</strong> {{ saving.goal }}<br>
            Currently saved: {{ saving.current_amount }}
        </p>
    </div><br>
    <p>
        <p><a href="{% url 'budgets:saving_update' pk=saving.id %}">Edit this saving</a></p>
        <p><a href="{% url 'budgets:saving_delete' pk=saving.id %}">Delete this saving</a></p>
        <p><a href="{% url 'budgets:saving_deposit' pk=saving.id %}">Deposit</a></p>
        <p><a href="{% url 'budgets:saving_withdraw' pk=saving.id %}">Withdraw</a></p>
    </p>
    <p class="saving-transactions">
        <p><h2>Latest transactions:</h2></p>
        {% for transaction in transactions %}
            <div>
                <p><strong><a href="{% url 'wallet:transaction_details' id=transaction.id %}">{{ transaction.name }}</a></strong><br>
                    Category: {{ transaction.category }}<br>
                    Amount: {{ transaction.amount }}<br>
                    Date: {{ transaction.date }}<br>
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

budgets/templates/savings/done.html
{% extends 'base.html' %}

{% block title %}Saving created{% endblock %}

{% block content %}
    <h1>Saving created!</h1>
    <p>New saving has been created.
        <p><a href="{% url 'budgets:saving_create' %}">Create new saving</a></p><br>
        <p><a href="{% url 'budgets:savings_list' %}">Go back to savings list</a></p>
    </p>
{% endblock %}

budgets/templates/savings/list.html
{% extends 'base.html' %}

{% block title %}Your Savings{% endblock %}

{% block intro %}<h2>Your Savings</h2>{% endblock %}

{% block content %}
    <div class="saving-list">
        {% for saving in savings %}
            <div class="saving">
                <li>
                    <a href="{{ saving.get_absolute_url }}">{{ saving.name }}</a> - Completed: {{ saving.saving_completion|floatformat:'1' }}%
                    (<a href="{% url 'budgets:saving_deposit' pk=saving.id %}">Deposit</a> / <a href="{% url 'budgets:saving_withdraw' pk=saving.id %}">Withdraw</a>)
                </li>
            </div><br>
        {% endfor %}
    </div>
{% endblock %}

{% block menu %}
    <div>
        <a href="{% url 'budgets:saving_create' %}">Create new saving</a>
    </div>
{% endblock %}

budgets/templates/savings/saving_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm saving delete{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

budgets/templates/savings/update.html
{% extends 'base.html' %}

{% block title %}Edit your saving: {{ saving.name }}{% endblock %}

{% block content %}
    <div>
        <p><h1>Edit your saving: {{ saving.name }}</h1></p>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
        </form>
    </div>

<script type="text/javascript">
  $(function(){
    $("#id_date_from").datepicker();
  });
</script>
{% endblock %}

budgets/templates/savings/withdraw.html
{% extends 'base.html' %}

{% block title %}Withdraw from saving: {{ saving.name }}{% endblock %}

{% block content %}
    <h1>Withdraw from saving: {{ saving.name }}</h1>
    <p>How much would you like to withdraw?</p>
    <form action="." method="post">
        {{ withdraw_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Withdraw"></p>
    </form>
{% endblock %}