api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_details'),
    url(r'^wallets/$', views.WalletListView.as_view(), name='wallet_list'),
    url(r'^wallets/(?P<pk>\d+)/$', views.WalletDetailView.as_view(), name='wallet_details'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<pk>\d+)/$', views.CategoryDetailView.as_view(), name='category_details'),
    url(r'^transactions/$', views.TransactionListView.as_view(), name='transaction_list'),
    url(r'^transactions/(?P<pk>\d+)/$', views.TransactionDetailView.as_view(), name='transaction_details'),
    url(r'^budgets/$', views.BudgetListView.as_view(), name='budget_list'),
    url(r'^budgets/(?P<pk>\d+)/$', views.BudgetDetailView.as_view(), name='budget_details'),
    url(r'^savings/$', views.SavingListView.as_view(), name='saving_list'),
    url(r'^savings/(?P<pk>\d+)/$', views.SavingDetailView.as_view(), name='saving_details'),
    url(r'^$', views.api_root, name='api_root'),
]

budgets/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^budget/list/$', views.budgets_list, name='budgets_list'),
    url(r'^budget/details/(?P<id>\d+)/$', views.budget_details, name='budget_details'),
    url(r'^budget/create/$', views.budget_create, name='budget_create'),
    url(r'^budget/delete/(?P<pk>\d+)/$', views.BudgetDelete.as_view(), name='budget_delete'),
    url(r'^budget/update/(?P<pk>\d+)/$', views.BudgetUpdate.as_view(), name='budget_update'),
    url(r'^savings/list/$', views.savings_list, name='savings_list'),
    url(r'^savings/details/(?P<id>\d+)/$', views.saving_details, name='saving_details'),
    url(r'^savings/create/$', views.saving_create, name='saving_create'),
    url(r'^savings/delete/(?P<pk>\d+)/$', views.SavingDelete.as_view(), name='saving_delete'),
    url(r'^savings/update/(?P<pk>\d+)/$', views.SavingUpdate.as_view(), name='saving_update'),
    url(r'^savings/deposit/(?P<pk>\d+)/$', views.saving_deposit, name='saving_deposit'),
    url(r'^savings/withdraw/(?P<pk>\d+)/$', views.saving_withdraw, name='saving_withdraw'),
]

transactions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^wallet/list/$', views.wallet_list, name='wallet_list'),
    url(r'^wallet/detail/(?P<id>\d+)/$', views.wallet_details, name='wallet_details'),
    url(r'^wallet/create/$', views.wallet_create, name='wallet_create'),
    url(r'^wallet/delete/(?P<pk>\d+)/$', views.WalletDelete.as_view(), name='wallet_delete'),
    url(r'^wallet/update/(?P<pk>\d+)/$', views.WalletUpdate.as_view(), name='wallet_update'),
    url(r'^category/list/$', views.category_list, name='category_list'),
    url(r'^category/detail/(?P<id>\d+)/$', views.category_details, name='category_details'),
    url(r'^category/create/$', views.category_create, name='category_create'),
    url(r'^category/delete/(?P<pk>\d+)/$', views.CategoryDelete.as_view(), name='category_delete'),
    url(r'^category/update/(?P<pk>\d+)/$', views.CategoryUpdate.as_view(), name='category_update'),
    url(r'^transaction/list/$', views.transaction_list, name='transactions_list'),
    url(r'^transaction/detail/(?P<id>\d+)/$', views.transaction_detail, name='transaction_details'),
    url(r'^transaction/create/$', views.transaction_create, name='transaction_create'),
    url(r'^transaction/delete/(?P<pk>\d+)/$', views.TransactionDelete.as_view(), name='transaction_delete'),
    url(r'^transaction/update/(?P<pk>\d+)/$', views.TransactionUpdate.as_view(), name='transaction_update'),
    url(r'^transaction/filter/$', views.transaction_filter, name='transaction_filter'),
    url(r'^transaction/create_recurring/$', views.recurring_transaction_create, name='recurring_create'),
    url(r'^export/csv/$', views.export_transactions_csv, name='export_transactions_csv'),
    url(r'^export/xls/$', views.export_transactions_xls, name='export_transactions_xls'),

]

wallet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^transactions/', include('transactions.urls', namespace='wallet')),
    url(r'^budgets/', include('budgets.urls', namespace='budgets')),
    url(r'^users/', include('users.urls')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^$', TemplateView.as_view(template_name='users/index.html')),
]

transactions/forms.py
from django import forms

from .models import Category, Transaction, Wallet


RECURRING_CHOICES = (
    ('daily', 'Daily'),
    ('weekly', 'Weekly'),
    ('monthly', 'Monthly'),
    ('yearly', 'Yearly'),
)


class WalletCreateForm(forms.ModelForm):
    field_order = ['name', 'balance', 'description']

    class Meta:
        model = Wallet
        fields = ('description', 'balance', 'name',)


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )


class TransactionCreateForm(forms.ModelForm):
    field_order = ['name', 'type', 'wallet', 'category', 'date', 'amount', 'notes', ]

    class Meta:
        model = Transaction
        fields = ('name', 'type', 'wallet', 'category', 'date', 'amount', 'notes',)

    def __init__(self, user, *args, **kwargs):
        super(TransactionCreateForm, self).__init__(*args, **kwargs)
        self.fields['wallet'] = forms.ModelChoiceField(queryset=Wallet.objects.filter(user=user))
        self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.filter(user=user))


class TransactionNextMonth(forms.Form):
    month = forms.IntegerField(widget=forms.HiddenInput)


class TransactionPrevMonth(forms.Form):
    month = forms.IntegerField(widget=forms.HiddenInput)


class RecurringTransactionForm(forms.Form):
    frequency = forms.ChoiceField(choices=RECURRING_CHOICES, required=True)
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=False)

transactions/views.py
import csv
import datetime

import xlwt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, UpdateView
from pure_pagination import PageNotAnInteger, Paginator

from budgets.models import Budget
from transactions.filters import TransactionFilter

from .forms import (CategoryCreateForm, TransactionCreateForm,
                    TransactionNextMonth, TransactionPrevMonth,
                    WalletCreateForm)
from .models import Category, Transaction, Wallet


@login_required
def wallet_list(request):
    current_user = request.user
    wallets = Wallet.objects.filter(user=current_user)
    return render(request, 'wallet/list.html', {'wallets': wallets})


@login_required
def wallet_details(request, id):
    wallet = get_object_or_404(Wallet, id=id)
    transactions = Transaction.objects.filter(wallet=wallet)
    return render(request, 'wallet/detail.html', {'wallet': wallet,
                                                  'transactions': transactions})


@login_required
def wallet_create(request):
    if request.method == 'POST':
        wallet_create_form = WalletCreateForm(request.POST)
        if wallet_create_form.is_valid():
            new_wallet = wallet_create_form.save(commit=False)
            new_wallet.user = request.user
            new_wallet.save()
            messages.success(request, 'Wallet created')
            return render(request, 'wallet/done.html')
    else:
        wallet_create_form = WalletCreateForm()
    return render(request, 'wallet/create.html', {'wallet_form': wallet_create_form})


class WalletDelete(DeleteView):
    model = Wallet
    template_name = 'wallet/wallet_confirm_delete.html'
    success_url = reverse_lazy('wallet:wallet_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(WalletDelete, self).dispatch(*args, **kwargs)


class WalletUpdate(UpdateView):
    model = Wallet
    fields = ['name', 'balance', 'description']
    template_name = 'wallet/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(WalletUpdate, self).dispatch(*args, **kwargs)


@login_required
def category_list(request):
    current_user = request.user
    categories = Category.objects.filter(user=current_user)
    return render(request, 'category/list.html', {'categories': categories})


@login_required
def category_details(request, id):
    category = get_object_or_404(Category, id=id)
    transactions = Transaction.objects.filter(category=category)
    return render(request, 'category/detail.html', {'category': category,
                                                    'transactions': transactions})


@login_required
def category_create(request):
    if request.method == 'POST':
        category_create_form = CategoryCreateForm(request.POST)
        if category_create_form.is_valid():
            new_category = category_create_form.save(commit=False)
            new_category.user = request.user
            new_category.save()
            messages.success(request, 'Category created')
            return render(request, 'category/done.html')
    else:
        category_create_form = CategoryCreateForm()
    return render(request, 'category/create.html', {'category_form': category_create_form})


class CategoryDelete(DeleteView):
    model = Category
    template_name = 'category/category_confirm_delete.html'
    success_url = reverse_lazy('wallet:category_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoryDelete, self).dispatch(*args, **kwargs)


class CategoryUpdate(UpdateView):
    model = Category
    template_name = 'category/update.html'
    form_class = CategoryCreateForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CategoryUpdate, self).dispatch(*args, **kwargs)


@login_required
def transaction_list(request, **kwargs):
    current_user = request.user

    if request.method == 'POST':
        next_month_form = TransactionNextMonth(request.POST)
        previous_month_form = TransactionPrevMonth(request.POST)

        if next_month_form.is_valid() and previous_month_form.is_valid():
            cd_next = next_month_form.cleaned_data
            cd_prev = previous_month_form.cleaned_data
            request.session['next_month'] = cd_next['month']
            request.session['prev_month'] = cd_prev['month']

            return HttpResponseRedirect('/transactions/transaction/list/')

    else:
        if request.session.get('next_month') is not None:
            next_month_form = TransactionNextMonth(
                initial={'month': request.session.get('next_month')+1})
            previous_month_form = TransactionPrevMonth(
                initial={'month': request.session.get('prev_month') - 1})
            objects = Transaction.objects.filter(user=current_user,
                                                 date__month=request.session.get('next_month'))
        else:
            next_month_form = TransactionNextMonth(
                initial={'month': datetime.date.today().month+1})
            previous_month_form = TransactionPrevMonth(
                initial={'month': datetime.date.today().month - 1})
            objects = Transaction.objects.filter(user=current_user,
                                                 date__month=datetime.date.today().month)

        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(objects, 10, request=request)
        transactions = p.page(page)
        return render(request, 'transaction/list.html',
                      {'transactions': transactions,
                       'next_month_form': next_month_form,
                       'prev_month_form': previous_month_form})


@login_required
def transaction_detail(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    return render(request, 'transaction/detail.html', {'transaction': transaction})


@login_required
def transaction_create(request):
    current_user = request.user
    if request.method == 'POST':
        transaction_create_form = TransactionCreateForm(current_user, request.POST)
        if transaction_create_form.is_valid():
            new_transaction = transaction_create_form.save(commit=False)
            new_transaction.user = current_user
            wallet = get_object_or_404(Wallet, name=new_transaction.wallet)
            new_transaction.wallet_balance_adjust(wallet, new_transaction)  # Adjust chosen wallet balance
            new_transaction.save()

            # assign budget if applicable:
            budgets = Budget.objects.filter(user=current_user)
            for budget in budgets:
                transactions = Transaction.objects.filter(
                    Q(date__gte=budget.date_from)
                    & Q(date__lte=budget.date_to)
                    & Q(category=budget.category))
                if budget.category == new_transaction.category and budget.active is True:
                    new_transaction.budget = budget
                    new_transaction.save()

                    # check if the budget has reached limit:
                    completion = budget.budget_completion(transactions)
                    if completion >= 100:
                        budget.finished, budget.finishing = True, False
                        messages.info(request,
                                      'You have reached the limit of your budget {}'
                                      .format(budget.name))
                    elif completion >= 80:
                        budget.finishing = True
                        messages.info(request,
                                      'You are almost at the limit of your budget {}'
                                      .format(budget.name))
                    budget.completion = completion
                    budget.save()
            messages.success(request, 'Transaction created')
            return render(request, 'transaction/done.html')
    else:

        transaction_create_form = TransactionCreateForm(current_user)
    return render(request, 'transaction/create.html',
                  {'transaction_form': transaction_create_form})


class TransactionDelete(DeleteView):
    model = Transaction
    template_name = 'transaction/transaction_confirm_delete.html'
    success_url = reverse_lazy('wallet:transactions_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TransactionDelete, self).dispatch(*args, **kwargs)


class TransactionUpdate(UpdateView):
    model = Transaction
    fields = ['name', 'type', 'wallet', 'category', 'date', 'amount', 'notes']
    template_name = 'transaction/update.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TransactionUpdate, self).dispatch(*args, **kwargs)


@login_required
def export_transactions_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="transactions.csv"'

    writer = csv.writer(response)
    writer.writerow(['Name', 'Type', 'Date', 'Wallet', 'Category', 'Amount', 'Notes'])

    transactions = Transaction.objects.filter(user=request.user).values_list(
        'name', 'type', 'date', 'wallet', 'category', 'amount', 'notes')
    for transaction in transactions:
        writer.writerow(transaction)
    return response


@login_required
def export_transactions_xls(request):
    response = HttpResponse(content_type='application/ms-excel')

transactions/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<link href="{% static 'css/styles.css' %}?version=17" rel="stylesheet" type="text/css" media="all">
<link href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Vollkorn:regular,italic,bold" rel="stylesheet" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<script src="js/IE9.js"></script>
<![endif]-->
<link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/themes/redmond/jquery-ui.css" rel="Stylesheet" />
<script language="javascript" type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js"></script>
<script>
    $(document).ready(function() {
        // messages timeout for 10 sec
        setTimeout(function() {
            $('.message').fadeOut('slow');
        }, 10000); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        $('.del-msg').live('click',function(){
            $('.del-msg').parent().attr('style', 'display:none;');
        })
    });
</script>
{% block head %}{% endblock %}
</head>
<body>
<div id="headerwrap">
    <header id="mainheader" class="bodywidth clear"> <img src="/static/images/logo.png" alt="" class="logo">
        <hgroup id="websitetitle">
            <h1><span class="bold">Wallets</span></h1>
            <h2>manage your money easily</h2>
        </hgroup>
        <nav>
            <ul>
                <li><a href="{% url 'main' %}">Home</a></li>
                <li><a href="{% url 'wallet:wallet_list' %}">Your Wallets</a></li>
                <li><a href="{% url 'wallet:category_list' %}">Categories</a></li>
                <li><a href="{% url 'wallet:transactions_list' %}">Transactions</a></li>
                <li><a href="{% url 'budgets:budgets_list' %}">Budgets</a></li>
                <li><a href="{% url 'budgets:savings_list' %}">Savings</a></li>
                <li>
                    {% if request.user.is_authenticated %}
                        Hello <a href="{% url 'user_details' %}">{{ request.user.first_name }}</a>,
                            <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                            <a href="{% url 'login' %}">Log-in</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
</div>
<aside id="introduction" class="bodywidth clear">
    <div id="introleft">
        <p>{% block intro %}{% endblock %}</p>
        <p>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message|safe }}
                                <a href="#" class="del-msg">✖</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </p>
    </div>
</aside>
<div id="maincontent" class="bodywidth clear">
    <div id="all-width">
        {% block allwidth %}
        {% endblock%}
    </div>
    <div id="aboutleft">
        {% block content %}
        {% endblock %}
    </div>
    <section id="articlesright">
        {% block menu %}
        {% endblock %}
    </section>
</div>
<script>
  $(document).ready(function() {

   var docHeight = $(window).height();
   var footerHeight = $('#mainfooter').height();
   var footerTop = $('#mainfooter').position().top + footerHeight;

   if (footerTop < docHeight) {
    $('#footerwrap').css('margin-top',  (docHeight - footerTop) + 'px');
   }
  });
</script>
<div id="footerwrap">
    <footer id="mainfooter" class="bodywidth clear">
        <nav class="clear">
            <ul>
                <li><<a href="{% url 'main' %}">Home</a></li>
                <li><a href="{% url 'wallet:wallet_list' %}">Your Wallets</a></li>
                <li><a href="{% url 'wallet:category_list' %}">Categories</a></li>
                <li><a href="{% url 'wallet:transactions_list' %}">Transactions</a></li>
                <li><a href="{% url 'budgets:budgets_list' %}">Budgets</a></li>
                <li><a href="{% url 'budgets:savings_list' %}">Savings</a></li>
            </ul>
        </nav>
        <p class="copyright">Website Template By <a target="_blank" href="http://www.tristarwebdesign.co.uk/">Tristar</a> &amp; Modified By <a target="_blank" href="http://www.os-templates.com/">OS Templates</a></p>
    </footer>
</div>
</body>
</html>

transactions/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>